//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Users
    {

        [Key]
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]

        public int UserId { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = "This field is required.")]
        public string name { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "This field is required.")]
        public string pass { get; set; }
        public int facNumber { get; set; }
        public int role { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> active { get; set; }
        public string errMessage { get; set; }
        

    }
}
